version: "3"

tasks:
  init:
    cmds:
      - touch App.java
  run:
    cmds:
      - javac App.java
      - java App
  version:
    cmds:
      - java -version
  clean:
    cmds:
      - rm -f *.java *.class
      - rm -rf out/
